[project]
name = "taichung-youbike-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lyoxin0o0", email = "wanthappy0o0@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
taichung-youbike-analysis = "taichung_youbike_analysis:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
